### ISSUE TITLE
Inlining is currently broken

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#111]
Big soundness test with
```
soottocfg.Options.v().setInlineCount(3);
soottocfg.Options.v().setInlineMaxSize(20);
```

gives the following:

```
**************************************
unsound: 1     exception: 22    imprecise: 16    correct: 101  

Unsound results:
  /Users/schaef/git/jayhorn/jayhorn/src/test/resources/horn-encoding/mem_precision/UnsatAliasing02.java
**************************************
```

**Comment by martinschaef** [comment]
fixed a few things, but `UnsatAliasing02.java` is still an issue. The inlining looks correct. I'd assume that the Alias Analysis gets confused somewhere.

**Comment by martinschaef** [comment]
Never mind, my ball. The issue is that the inlined method may exit exceptionally, but after the inlining, we don't check if that happens, so there is a path that reaches the assertion where `m` terminated with a `NullPointerException`.

**Comment by rodykersten** [comment]
Fixed a pretty tricky problem in the simplifier. However, this is now happening for arrays/UnsatArray.java...

**Comment by martinschaef** [comment]
I tried to minimize the example a bit. The following is the shortest I could come up with:
```java

public class A {
  public int i;
  public static void main(String[] args) {	
    A[] as = new A[2];
    A tmp = as[0];
    int x = tmp.i;
    assert false;
  }
}
```
This is broken with inlining. It is works if the array is of a primitive type like `int`. So the `assume false` is introduced when we access `tmp.i`. I'll look into that.

**Comment by martinschaef** [comment]
This is actually unsound, even without inlining ...

**Comment by martinschaef** [comment]
The example above is fixed with #112.

**Comment by martinschaef** [comment]
I'll close it for now since all bugs are gone. But we still don't have an example where inlining actually makes things a lot better.
